try{
    return "Success"
}catch(err){
    return `Error: ${err}`;
}
